"""initial tables

Revision ID: 995318d08496
Revises: 
Create Date: 2025-11-19 16:32:32.919133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995318d08496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('grdp', sa.Integer(), nullable=True),
    sa.Column('basic_beneficiaries', sa.Integer(), nullable=True),
    sa.Column('multicultural_hh', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('divorce', sa.Integer(), nullable=True),
    sa.Column('child_facility', sa.Integer(), nullable=True),
    sa.Column('child_user', sa.Integer(), nullable=True),
    sa.Column('single_parent', sa.Integer(), nullable=True),
    sa.Column('birth_cnt', sa.Integer(), nullable=True),
    sa.Column('academy_cnt', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('region_data')
    op.drop_table('prediction_log')
    # ### end Alembic commands ###
